apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: hasura
        image: hasura/graphql-engine:v2.39.2
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: todos.todos-postgresql.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todos.todos-postgresql.credentials.postgresql.acid.zalan.do
              key: password
        - name: POSTGRES_DATABASE
          value: todos
        - name: POSTGRES_HOST
          value: todos-postgresql.default.svc.cluster.local
        - name: POSTGRES_PORT
          value: "5432"
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DATABASE)
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "true"